Continued work on ios testsuite

diff --git a/testsuite/Makefile b/testsuite/Makefile
--- a/testsuite/Makefile
+++ b/testsuite/Makefile
@@ -57,6 +57,28 @@ cross-compile-here:
 	  $(MAKE) BASEDIR=$(BASEDIR) DIR=$(DIR) cross-compile; \
 	fi
 
+.PHONY: cross-run
+cross-run:
+	@if [ -z "$(IP)" ]; then echo "Variable IP not set (set this to the IP address of the server)" >&2; exit 1; fi
+	@if [ -z "$(PORT)" ]; then echo "Variable PORT not set (set this to the port of the server)" >&2; exit 1; fi
+	@for dir in tests/*; do \
+	  $(MAKE) $(NO_PRINT) cross-run-here DIR=$$dir; \
+	done 2>&1 | tee _log
+
+.PHONY: cross-run-here
+cross-run-here:
+	@if [ ! -f $(DIR)/Makefile ]; then \
+	  for dir in $(DIR)/*; do \
+	    if [ -d $$dir ]; then \
+	      $(MAKE) cross-run-here DIR=$$dir; \
+	    fi; \
+	  done; \
+	else \
+	  echo "Running tests from '$$DIR' ..."; \
+	  cd $(DIR) && \
+	  $(MAKE) TERM=dumb BASEDIR=$(BASEDIR) cross-run || echo '=> unexpected error'; \
+	fi
+
 .PHONY: list
 list: lib
 	@if [ -z "$(FILE)" ]; \
diff --git a/testsuite/makefiles/Makefile.one b/testsuite/makefiles/Makefile.one
--- a/testsuite/makefiles/Makefile.one
+++ b/testsuite/makefiles/Makefile.one
@@ -68,7 +68,11 @@ run:
 	&& echo " => passed" || echo " => failed"
 
 .PHONY: cross-compile
-cross-compile: $(ML_FILES) $(CMI_FILES) $(CMX_FILES) $(MAIN_MODULE).ml
+cross-compile:
+	@if [ ! -f "$(MAIN_MODULE)".nocross ]; then $(MAKE) cross-compile-1; fi
+
+.PHONY: cross-compile-1
+cross-compile-1: $(ML_FILES) $(CMI_FILES) $(CMX_FILES) $(MAIN_MODULE).ml
 	@for file in $(C_FILES); do \
 	  $(NATIVECC) $(NATIVECCCOMPOPTS) -c -I$(CTOPDIR)/byterun $$file.c; \
 	done;
@@ -90,6 +94,18 @@ cross-compile: $(ML_FILES) $(CMI_FILES) $(CMX_FILES) $(MAIN_MODULE).ml
 		      $(CMX_FILES) \
 		      "$$out".ml; \
 	echo "$(DIR)/$$out" >>$(BASEDIR)/modules
+
+.PHONY: cross-run
+cross-run:
+	@if [ ! -f "$(MAIN_MODULE)".nocross ]; then $(MAKE) cross-run-1; fi
+
+.PHONY: cross-run-1
+cross-run-1:
+	@printf " ... testing against testserver\n"
+	@echo "$(DIR)/$(MAIN_MODULE)" | nc "$(IP)" "$(PORT)" >$(MAIN_MODULE).result
+	@{ $(DIFF) $(MAIN_MODULE).reference $(MAIN_MODULE).result >/dev/null; } \
+	&& echo " => passed" || echo " => failed"
+
 
 .PHONY: promote
 promote: defaultpromote
diff --git a/testsuite/makefiles/Makefile.several b/testsuite/makefiles/Makefile.several
--- a/testsuite/makefiles/Makefile.several
+++ b/testsuite/makefiles/Makefile.several
@@ -118,6 +118,7 @@ cross-compile-1:
 	  if [ -f "$$base.precheck" ]; then \
 	    CANKILL=$(CANKILL) sh "$$base.precheck" || continue; \
 	  fi; \
+	  if [ -f "$$base".nocross ]; then continue; fi; \
 	  out="cross_$${dirid}_$$k"; \
 	  printf "let exit _ = raise Exit\n" >"$$out".ml ; \
 	  printf "let testname = \""$(DIR)"/$$base\";;\n" >>"$$out".ml; \
@@ -129,9 +130,31 @@ cross-compile-1:
                       -w a $(ADD_COMPFLAGS) $(ADD_OPTFLAGS) \
 		      $(O_FILES) \
 		      -I $(OTOPDIR)/testsuite/lib "$$out".ml; \
+	  ln -s "$$out".cmxa "$$base".cmxa; \
 	  k=$$(( k+1 )); \
 	  echo "$(DIR)/$$out" >> $(BASEDIR)/modules; \
 	done
+
+.PHONY: cross-run
+cross-run:
+	@printf " ... testing against testserver\n"
+	@for file in *.cmxa; do \
+	  base=`basename $$file .cmxa`; \
+	  case "$$base" in cross_*) continue;; esac; \
+	  if [ -f $$base/precheck ]; then \
+	    CANKILL=$(CANKILL) sh $$base/precheck || continue; \
+	  fi; \
+	  if [ -f $$base.runner ]; then continue; fi; \
+	  if [ -f "$$base".nocross ]; then continue; fi; \
+	  printf " ... testing '$$base.ml':"; \
+	  echo "$(DIR)/$$base" | nc "$(IP)" "$(PORT)" >$$base.result && \
+          if [ -f $$base.checker ]; then \
+	      DIFF="$(DIFF)" SORT="$(SORT)" sh $$base.checker; \
+	  else \
+	      $(DIFF) $$base.reference $$base.result >/dev/null; \
+	  fi \
+	  && echo " => passed" || echo " => failed"; \
+        done
 
 .PHONY: promote
 promote: defaultpromote
